#
# Makefile
#
# Makefile for Poco NetSSL Samples
#

.DEFAULT all:
	$(MAKE) -C HTTPSTimeServer $(MAKECMDGOALS)
	$(MAKE) -C EVHTTPSTimeServer $(MAKECMDGOALS)
	$(MAKE) -C EVHTTPSFormServer $(MAKECMDGOALS)
	$(MAKE) -C download $(MAKECMDGOALS)
	$(MAKE) -C Mail $(MAKECMDGOALS)
	$(MAKE) -C TwitterClient $(MAKECMDGOALS)
